spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    password: root
    url: jdbc:mysql://localhost:3306/BookDatabase?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /jsp_pages/
      suffix: .jsp
